POST https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/train

# POST를 train으로
GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/0/right/0

GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/1/right/0

GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/0/right/1

GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/1/right/1xq