###
# POST https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/train/all #all은 안되나보다
###

#AND 트레이닝
POST https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/train/and
###
#OR 트레이닝
POST https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/train/or
###
#XOR 트레이닝
POST https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/train/xor
###


GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/xor/left/0/right/0
#0,0인 경우
###
GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/1/right/0
#1,0인경우
###
GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/0/right/1
#0,1 인경우
###
GET https://crispy-guacamole-g4x7r5r9qw6wh9697-8000.app.github.dev/predict/left/1/right/1
#1,1 인경우

